### PR TITLE
Implement new sampler API

### PR DESCRIPTION
**Pull request by cdcapano**
Branch to implement the new API.

Depends on #35.

### CODE REVIEW

**Comment by johnveitch** [comment]
For the nested samplers that need to sample the entire prior it would be useful (or even essential) to have a bounding box for the prior support in the Model class, i.e. the maximum range of the sampling parameters allowed by the prior.

**Comment by cdcapano** [comment]
@johnveitch Noted, though I (or someone) will do it in another PR. That should be easy to add since most of the distributions used in the prior have ``bounds`` attributes. But what happens if the prior has no finite bounds (e.g., a Gaussian distribution, or if one of the sampling parameters is a logit transform)? Would we require that the sampling parameters *must* be bounded if using a nested sampler?

**Comment by cdcapano** [comment]
Depends on #39.

**Comment by cdcapano** [comment]
Instead of doing this as a single large PR onto master, I've created a branch for this project, `new_sampler_api`. The work so far on this PR has been moved to #68, which is a pull request on to that branch instead of master. Once #68 is merged, I'll open up a new PR to track changes between that branch and master.

**Pull request closed without merging**
