### PR TITLE
Rename the likelihood module to models

### PR DESCRIPTION
**Pull request by cdcapano**
This renames the likelihood module to `models`. Also renames all instances of `likelihood_evaluator` to `model` in the sampler module and elsewhere. The `BaseLikelihoodEvaluator` has been renamed `Model` and `DataBasedLikelihoodEvaluator` has been renamed `DataModel`.

Depends on #33.

### CODE REVIEW

**Review by duncanmmacleod — DISMISSED** [review]
LGTM

**Comment by cdcapano** [comment]
Also renamed `sampling_parameters` --> `sampling_params`, `variable_args` --> `variable_params`; `static_args` --> `static_params` to make terminology consistent.

This depends on the next pycbc release, so putting on hold until that's out (should be today or tomorrow).

**Comment by cdcapano** [comment]
Actually, looks like I can merge this now without failing Travis. This will break gwin if you don't have current pycbc master installed, but the new release should come out in the next few days. Would be good to merge this now, to simplify #36.

**Comment by vivienr** [comment]
Should we have codeclimate setting's relaxed a little?

**Review by vivienr — APPROVED** [review]
LGTM

**Pull request merged**
