### PR TITLE
Adding doc to explain likelihood marginalization

### PR DESCRIPTION
**Pull request by hoyc1**
This is an extension of pull request #56 which addresses issue #37.

### CODE REVIEW

**Comment by cdcapano** [comment]
@hoyc1 Is this a work in progress? If so, stick "WIP" in the title until it's ready.

**Comment by hoyc1** [comment]
@cdcapano, yes it is. Sorry!

**Comment by hoyc1** [comment]
@cdcapano, I think this is ready.

**Review by cdcapano — APPROVED** [review]
LGTM

**Pull request merged**
