### PR TITLE
Add acl-based burn in (PRs 2112 and 2121 in pycbc)

### PR DESCRIPTION
**Pull request by cdcapano**
This adds an acl-based burn-in function to `burn_in.py`. This is a mirror of PRs 2112 and 2121 in pycbc.

### CODE REVIEW

**Review by duncanmmacleod — CHANGES_REQUESTED** [review]
This PR undoes a large number of pep8-related changes made in #4, these should be reinstated. It would likely be cleaner to manually copy across the changes from the relevant pycbc PR into the updated `gwin` files, rather than copying the files themselves wholesale.

**Comment by cdcapano** [comment]
@duncanmmacleod Oh, I didn't realize #4 touched `burn_in.py`... when I created this I just diffed `gwin/burn_in.py` to `pycbc/inference/burn_in.py` and applied the resultant patch. I can just manually copy the relevant lines over.

**Comment by duncanmmacleod** [comment]
@cdcapano, #4 touched every module in the repo (more or less).

**Comment by cdcapano** [comment]
@duncanmmacleod Ok, I redid the patch, taking into account the changes in #4.

**Review by duncanmmacleod — APPROVED** [review]

**Pull request merged**
